# -*- coding: utf-8 -*-
"""ISTEMA DE GESTIÓN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1akc5g5TuXqvYc9Opo-mC_vdF0hlz33Hs
"""

# ==========================================
# SISTEMA DE GESTIÓN - SOFTWARE FJ
# ==========================================
# Desarrollado por: JHON JARVIS MARTINEZ ACUÑA
# Curso: Programacion
# Tutor: YAHITH YAMID GUTIERREZ GOMEZ
# Se integra:
# - POO (abstracción, herencia, polimorfismo, encapsulación)
# - Excepciones personalizadas
# - Logs
# - Menú interactivo
# - Simulación (10+ casos)
# - Pruebas automáticas

from abc import ABC, abstractmethod
import logging

# ==========================================
# CONFIGURACIÓN DE LOGS
# ==========================================
logging.basicConfig(
    filename="logs.txt",
    level=logging.ERROR,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

# ==========================================
# EXCEPCIONES PERSONALIZADAS
# ==========================================
class ClienteError(Exception): pass
class ServicioError(Exception): pass
class ReservaError(Exception): pass

# ==========================================
# CLASE ABSTRACTA
# ==========================================
class Entidad(ABC):
    @abstractmethod
    def mostrar_info(self): pass

# ==========================================
# CLIENTE
# ==========================================
class Cliente(Entidad):
    def __init__(self, nombre, email):
        if not nombre:
            raise ClienteError("Nombre vacío")
        if "@" not in email:
            raise ClienteError("Email inválido")
        self.__nombre = nombre
        self.__email = email

    def mostrar_info(self):
        return f"Cliente: {self.__nombre} - {self.__email}"

    def get_nombre(self): return self.__nombre

# ==========================================
# SERVICIOS
# ==========================================
class Servicio(Entidad, ABC):
    def __init__(self, nombre, costo_base):
        self.nombre = nombre
        self.costo_base = costo_base

    @abstractmethod
    def calcular_costo(self, duracion): pass

class ServicioSala(Servicio):
    def calcular_costo(self, horas): return self.costo_base * horas
    def mostrar_info(self): return f"Sala: {self.nombre} - {self.costo_base}"

class ServicioEquipo(Servicio):
    def calcular_costo(self, dias): return self.costo_base * dias
    def mostrar_info(self): return f"Equipo: {self.nombre} - {self.costo_base}"

class ServicioAsesoria(Servicio):
    def calcular_costo(self, horas, descuento=0):
        return (self.costo_base * horas) - descuento
    def mostrar_info(self): return f"Asesoría: {self.nombre} - {self.costo_base}"

# ==========================================
# RESERVA
# ==========================================
class Reserva:
    def __init__(self, cliente, servicio, duracion):
        if not isinstance(cliente, Cliente):
            raise ReservaError("Cliente inválido")
        if not isinstance(servicio, Servicio):
            raise ReservaError("Servicio inválido")
        if duracion <= 0:
            raise ReservaError("Duración inválida")

        self.cliente = cliente
        self.servicio = servicio
        self.duracion = duracion
        self.estado = "Pendiente"

    def confirmar(self): self.estado = "Confirmada"
    def cancelar(self): self.estado = "Cancelada"

    def procesar(self):
        try:
            costo = self.servicio.calcular_costo(self.duracion)
            self.confirmar()
            return costo
        except Exception as e:
            logging.error(e)
            self.cancelar()

# ==========================================
# DATOS
# ==========================================
clientes = []
servicios = []
reservas = []

# ==========================================
# MENÚ INTERACTIVO
# ==========================================
def menu():
    while True:
        print("\n--- MENÚ ---")
        print("1. Crear cliente")
        print("2. Ver clientes")
        print("3. Crear reserva")
        print("4. Ver reservas")
        print("5. Salir")

        opcion = input("Seleccione opción: ")

        try:
            if opcion == "1":
                nombre = input("Nombre: ")
                email = input("Email: ")
                cliente = Cliente(nombre, email)
                clientes.append(cliente)
                print("Cliente creado")

            elif opcion == "2":
                for c in clientes:
                    print(c.mostrar_info())

            elif opcion == "3":
                if not clientes or not servicios:
                    raise ReservaError("No hay datos")
                cliente = clientes[0]
                servicio = servicios[0]
                reserva = Reserva(cliente, servicio, 2)
                reservas.append(reserva)
                print("Reserva creada")

            elif opcion == "4":
                for r in reservas:
                    print(f"{r.cliente.get_nombre()} - {r.estado}")

            elif opcion == "5":
                break

        except Exception as e:
            logging.error(e)
            print("Error controlado")

# ==========================================
# SIMULACIÓN (10+ CASOS)
# ==========================================
def simulacion():
    print("\n--- SIMULACIÓN ---")

    try: clientes.append(Cliente("Ana","ana@mail.com"))
    except Exception as e: logging.error(e)

    try: clientes.append(Cliente("","mal"))
    except Exception as e: logging.error(e)

    servicios.extend([
        ServicioSala("Sala1",100),
        ServicioEquipo("Equipo1",50),
        ServicioAsesoria("Asesoria1",200)
    ])

    # 10 casos
    for i in range(10):
        try:
            r = Reserva(clientes[0], servicios[0], i-3)
            reservas.append(r)
        except Exception as e:
            logging.error(e)

    for r in reservas:
        try:
            costo = r.procesar()
            print("Reserva:", r.estado, "Costo:", costo)
        except Exception as e:
            logging.error(e)

# ==========================================
# PRUEBAS AUTOMÁTICAS
# ==========================================
def pruebas():
    print("\n--- PRUEBAS ---")

    try:
        Cliente("","x")
    except ClienteError:
        print("Prueba cliente inválido OK")

    try:
        Reserva("x","y",-1)
    except ReservaError:
        print("Prueba reserva inválida OK")

# ==========================================
# MAIN
# ==========================================
if __name__ == "__main__":
    simulacion()      # Ejecuta pruebas automáticas del sistema
    pruebas()         # Ejecuta validaciones
    menu()            # Sistema interactivo